import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

export type Language = 'en' | 'es' | 'ja' | 'ko' | 'zh-CN' | 'zh-TW';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'header.title': 'JobboCat',
    'header.features': 'Features',
    'header.about': 'About',
    'header.login': 'Login',
    
    // Welcome Page
    'welcome.badge.loading': 'Loading...',
    'welcome.badge.looking': 'people looking for jobs right now',
    'welcome.badge.person': 'person',
    'welcome.badge.first': 'Be the first to join!',
    'welcome.badge.youare': "You're #",
    'welcome.early.title': 'Early Adopter!',
    'welcome.early.message': "You're one of the first 10 members! Welcome to the community! 🚀",
    'welcome.title': "You're Not Alone",
    'welcome.subtitle': 'See how many people are in the same journey. Connect, share experiences, and support each other.',
    'welcome.field.select': 'Select your field',
    'welcome.field.technology': 'Technology',
    'welcome.field.design': 'Design',
    'welcome.field.business': 'Business',
    'welcome.field.marketing': 'Marketing',
    'welcome.field.education': 'Education',
    'welcome.field.healthcare': 'Healthcare',
    'welcome.button.join': 'Join the Community',
    
    // Character Creator
    'character.title': 'Create Your Cat Character',
    'character.subtitle': 'Customize your character and join the community',
    'character.preview': 'Character Preview',
    'character.preview.placeholder': 'Select a cat to preview',
    'character.cat.type': 'Cat Type',
    'character.outfit': 'Outfit',
    'character.notselected': 'Not selected',
    'character.complete': 'Character Complete!',
    'character.button.back': '← Back',
    'character.button.join': 'Join Community →',
    
    // Cat Types
    'cat.tabby': 'Tabby Cat',
    'cat.tuxedo': 'Tuxedo Cat',
    'cat.calico': 'Calico Cat',
    'cat.siamese': 'Siamese Cat',
    'cat.ginger': 'Ginger Cat',
    'cat.white': 'White Cat',
    
    // Outfits
    'outfit.casual': 'Casual',
    'outfit.casual.desc': 'Comfy & Relaxed',
    'outfit.business': 'Business',
    'outfit.business.desc': 'Professional Look',
    'outfit.creative': 'Creative',
    'outfit.creative.desc': 'Artsy & Unique',
    'outfit.sporty': 'Sporty',
    'outfit.sporty.desc': 'Active & Energetic',
    'outfit.formal': 'Formal',
    'outfit.formal.desc': 'Elegant Style',
    'outfit.tech': 'Tech',
    'outfit.tech.desc': 'Modern & Techy',
    
    // Lobby Page
    'lobby.stats.title': 'Lobby Info',
    'lobby.stats.jobseekers': 'People Looking for Jobs',
    'lobby.stats.samefield': 'Same Field',
    'lobby.stats.focusing': 'Currently Focusing',
    'lobby.stats.online': 'Online',
    'lobby.cat.dialogue': 'Let\'s focus for 25 minutes, and I\'ll give you a new accessory!',
    'lobby.focus.button.start': 'Start 25-Minute Focus',
    'lobby.focus.button.focusing': 'Focusing... (25:00)',
    'lobby.focus.progress': 'Today\'s Progress',
    'lobby.focus.complete': '🎉 Daily Goal Achieved!',
    'lobby.focus.overlay': 'Focusing...',
    'lobby.others.title': 'Others Focusing',
    'lobby.others.minutes': 'min',
    'lobby.messages.title': 'Public Message Stream',
    'lobby.messages.placeholder': 'Share what you\'re working on, e.g.: Working on OS lab',
    'lobby.messages.hint': '💡 Using dummy data for now, will connect to WebSocket/Redis later',

    // About Page
    'about.title': 'About Jobbo Cat',
    'about.subtitle': 'A community-driven platform connecting job seekers and fostering meaningful professional relationships',
    'about.mission.title': 'Our Mission',
    'about.mission.p1': 'Job searching can be isolating and overwhelming. Jobbo Cat is built on the belief that',
    'about.mission.highlight': 'you\'re not alone',
    'about.mission.p2': 'in your journey.',
    'about.mission.p3': 'We create a space where job seekers can connect, share experiences, support each other, and build meaningful professional relationships. Together, we make the job search journey less daunting and more collaborative.',
    'about.creator.title': 'Meet the Creator',
    'about.creator.name': 'Lianrui Sun',
    'about.creator.role': 'Full Stack Developer & Product Designer',
    'about.creator.bio': 'A passionate developer with expertise in building scalable web applications and creating intuitive user experiences. Currently based in Canada, with a strong background in computer science and software engineering.',
    'about.creator.education': 'Education:',
    'about.creator.education.value': 'Bachelor of Computer Science, University of Waterloo (Expected 2026)',
    'about.creator.skills': 'Skills:',
    'about.creator.skills.value': 'React, TypeScript, Node.js, Python, Cloud Architecture, UI/UX Design',
    'about.creator.experience': 'Experience:',
    'about.creator.experience.value': 'Full Stack Development, Product Design, Community Building',
    'about.creator.quote': '"Having experienced the challenges of job searching firsthand, I built Jobbo Cat to create the supportive community I wished existed. Let\'s navigate this journey together."',
    'about.values.title': 'Our Values',
    'about.values.community.title': 'Community First',
    'about.values.community.desc': 'Building authentic connections and supporting each other',
    'about.values.transparency.title': 'Transparency',
    'about.values.transparency.desc': 'Open, honest communication and real-time visibility',
    'about.values.empowerment.title': 'Empowerment',
    'about.values.empowerment.desc': 'Providing tools and support for your success',

    // Features Page
    'features.title': 'Powerful Features',
    'features.subtitle': 'Everything you need to succeed in your job search journey',
    'features.live.title': 'Real-Time Visitor Count',
    'features.live.desc': 'See exactly how many people are online and active right now. Know you\'re not alone.',
    'features.auth.title': 'Secure Authentication',
    'features.auth.desc': 'Sign in securely with Supabase. Your data is protected and your privacy is respected.',
    'features.character.title': 'Character Customization',
    'features.character.desc': 'Create your own unique cat character. Choose types, outfits, and accessories to express yourself.',
    'features.profile.title': 'Personal Profiles',
    'features.profile.desc': 'Customize your username, bio, and character. Express yourself and connect with others.',
    'features.focus.title': 'Focus Sessions',
    'features.focus.desc': 'Track your productivity with Pomodoro-style focus timers. Build consistent study habits.',
    'features.community.title': 'Community Support',
    'features.community.desc': 'Connect with job seekers in your field. Share experiences and support each other.',
    'features.multilang.title': 'Multi-language Support',
    'features.multilang.desc': 'Available in English, Spanish, Japanese, Korean, and Chinese (Simplified & Traditional).',
    'features.responsive.title': 'Fully Responsive',
    'features.responsive.desc': 'Works seamlessly on desktop, tablet, and mobile devices. Study anywhere, anytime.',
  },
  es: {
    // Header
    'header.title': 'JobboCat',
    'header.features': 'Características',
    'header.about': 'Acerca de',
    'header.login': 'Iniciar sesión',
    
    // Welcome Page
    'welcome.badge.loading': 'Cargando...',
    'welcome.badge.looking': 'personas buscando trabajo ahora',
    'welcome.badge.person': 'persona',
    'welcome.badge.first': '¡Sé el primero en unirte!',
    'welcome.badge.youare': 'Eres #',
    'welcome.early.title': '¡Adoptador Temprano!',
    'welcome.early.message': '¡Eres uno de los primeros 10 miembros! ¡Bienvenido a la comunidad! 🚀',
    'welcome.title': 'No Estás Solo',
    'welcome.subtitle': 'Ve cuántas personas están en el mismo viaje. Conéctate, comparte experiencias y apóyense mutuamente.',
    'welcome.field.select': 'Selecciona tu campo',
    'welcome.field.technology': 'Tecnología',
    'welcome.field.design': 'Diseño',
    'welcome.field.business': 'Negocios',
    'welcome.field.marketing': 'Marketing',
    'welcome.field.education': 'Educación',
    'welcome.field.healthcare': 'Salud',
    'welcome.button.join': 'Unirse a la Comunidad',
    
    // Character Creator
    'character.title': 'Crea Tu Personaje Gato',
    'character.subtitle': 'Personaliza tu personaje y únete a la comunidad',
    'character.preview': 'Vista Previa',
    'character.preview.placeholder': 'Selecciona un gato para previsualizar',
    'character.cat.type': 'Tipo de Gato',
    'character.outfit': 'Atuendo',
    'character.notselected': 'No seleccionado',
    'character.complete': '¡Personaje Completo!',
    'character.button.back': '← Atrás',
    'character.button.join': 'Unirse →',
    
    // Cat Types
    'cat.tabby': 'Gato Atigrado',
    'cat.tuxedo': 'Gato Esmoquin',
    'cat.calico': 'Gato Calicó',
    'cat.siamese': 'Gato Siamés',
    'cat.ginger': 'Gato Naranja',
    'cat.white': 'Gato Blanco',
    
    // Outfits
    'outfit.casual': 'Casual',
    'outfit.casual.desc': 'Cómodo y Relajado',
    'outfit.business': 'Negocios',
    'outfit.business.desc': 'Look Profesional',
    'outfit.creative': 'Creativo',
    'outfit.creative.desc': 'Artístico y Único',
    'outfit.sporty': 'Deportivo',
    'outfit.sporty.desc': 'Activo y Energético',
    'outfit.formal': 'Formal',
    'outfit.formal.desc': 'Estilo Elegante',
    'outfit.tech': 'Tecnológico',
    'outfit.tech.desc': 'Moderno y Técnico',
    
    // Lobby Page
    'lobby.stats.title': 'Información del Lobby',
    'lobby.stats.jobseekers': 'Personas Buscando Trabajo',
    'lobby.stats.samefield': 'Mismo Campo',
    'lobby.stats.focusing': 'Enfocándose Ahora',
    'lobby.stats.online': 'En Línea',
    'lobby.cat.dialogue': '¡Enfoquémonos 25 minutos y te daré un nuevo accesorio!',
    'lobby.focus.button.start': 'Comenzar Enfoque de 25 Minutos',
    'lobby.focus.button.focusing': 'Enfocando... (25:00)',
    'lobby.focus.progress': 'Progreso de Hoy',
    'lobby.focus.complete': '🎉 ¡Meta Diaria Completada!',
    'lobby.focus.overlay': 'Enfocando...',
    'lobby.others.title': 'Otros Enfocándose',
    'lobby.others.minutes': 'min',
    'lobby.messages.title': 'Mensajes Públicos',
    'lobby.messages.placeholder': 'Comparte en qué estás trabajando, ej.: Trabajando en laboratorio de SO',
    'lobby.messages.hint': '💡 Usando datos de prueba, se conectará a WebSocket/Redis más tarde',
    
    // About Page
    'about.title': 'Acerca de Jobbo Cat',
    'about.subtitle': 'Una plataforma impulsada por la comunidad que conecta a buscadores de empleo y fomenta relaciones profesionales significativas',
    'about.mission.title': 'Nuestra Misión',
    'about.mission.p1': 'Buscar trabajo puede ser aislante y abrumador. Jobbo Cat se basa en la creencia de que',
    'about.mission.highlight': 'no estás solo',
    'about.mission.p2': 'en tu viaje.',
    'about.mission.p3': 'Creamos un espacio donde los buscadores de empleo pueden conectarse, compartir experiencias, apoyarse mutuamente y construir relaciones profesionales significativas. Juntos, hacemos que el viaje de búsqueda de empleo sea menos desalentador y más colaborativo.',
    'about.creator.title': 'Conoce al Creador',
    'about.creator.name': 'Lianrui Sun',
    'about.creator.role': 'Desarrollador Full Stack y Diseñador de Productos',
    'about.creator.bio': 'Un desarrollador apasionado con experiencia en la construcción de aplicaciones web escalables y la creación de experiencias de usuario intuitivas. Actualmente basado en Canadá, con una sólida formación en ciencias de la computación e ingeniería de software.',
    'about.creator.education': 'Educación:',
    'about.creator.education.value': 'Licenciatura en Ciencias de la Computación, Universidad de Waterloo (Esperado 2026)',
    'about.creator.skills': 'Habilidades:',
    'about.creator.skills.value': 'React, TypeScript, Node.js, Python, Arquitectura en la Nube, Diseño UI/UX',
    'about.creator.experience': 'Experiencia:',
    'about.creator.experience.value': 'Desarrollo Full Stack, Diseño de Productos, Construcción de Comunidades',
    'about.creator.quote': '"Habiendo experimentado los desafíos de la búsqueda de empleo de primera mano, construí Jobbo Cat para crear la comunidad de apoyo que deseaba que existiera. Naveguemos este viaje juntos."',
    'about.values.community.title': 'Comunidad Primero',
    'about.values.community.desc': 'Construyendo conexiones auténticas y apoyándonos mutuamente',
    'about.values.transparency.title': 'Transparencia',
    'about.values.transparency.desc': 'Comunicación abierta y honesta y visibilidad en tiempo real',
    'about.values.empowerment.title': 'Empoderamiento',
    'about.values.empowerment.desc': 'Proporcionando herramientas y apoyo para tu éxito',
    
    // Features Page
    'features.title': 'Características',
    'features.subtitle': 'Todo lo que necesitas para tener éxito en tu búsqueda de empleo',
    'features.live.title': 'Contador en Vivo',
    'features.live.desc': 'Ve cuántas personas están buscando trabajo activamente en tiempo real. No estás solo en este viaje.',
    'features.auth.title': 'Autenticación Segura',
    'features.auth.desc': 'Inicia sesión con correo/contraseña o Google OAuth. Tus datos están protegidos con seguridad de nivel empresarial.',
    'features.character.title': 'Personalización de Personajes',
    'features.character.desc': 'Crea tu propio personaje de gato único con varios diseños, sombreros, mesas y accesorios.',
    'features.profile.title': 'Perfiles Personales',
    'features.profile.desc': 'Personaliza tu nombre de usuario, biografía y personaje. Exprésate y conecta con otros.',
    'features.focus.title': 'Sesiones de Concentración',
    'features.focus.desc': 'Rastrea tu productividad con temporizadores de enfoque estilo Pomodoro. Construye hábitos de estudio consistentes.',
    'features.community.title': 'Apoyo Comunitario',
    'features.community.desc': 'Conéctate con buscadores de empleo en tu campo. Comparte experiencias y apóyense mutuamente.',
    'features.multilang.title': 'Soporte Multilingüe',
    'features.multilang.desc': 'Disponible en inglés, español, japonés, coreano y chino (simplificado y tradicional).',
    'features.responsive.title': 'Totalmente Responsivo',
    'features.responsive.desc': 'Funciona perfectamente en escritorio, tableta y dispositivos móviles. Estudia en cualquier lugar, en cualquier momento.',
  },
  ja: {
    // Header
    'header.title': 'JobboCat',
    'header.features': '機能',
    'header.about': '概要',
    'header.login': 'ログイン',
    
    // Welcome Page
    'welcome.badge.loading': '読み込み中...',
    'welcome.badge.looking': '人が今仕事を探しています',
    'welcome.badge.person': '人',
    'welcome.badge.first': '最初の参加者になろう！',
    'welcome.badge.youare': 'あなたは #',
    'welcome.early.title': 'アーリーアダプター！',
    'welcome.early.message': '最初の10人のメンバーの一人です！コミュニティへようこそ！🚀',
    'welcome.title': 'あなたは一人じゃない',
    'welcome.subtitle': '同じ旅をしている人の数を見てください。つながり、経験を共有し、お互いをサポートしましょう。',
    'welcome.field.select': '分野を選択',
    'welcome.field.technology': 'テクノロジー',
    'welcome.field.design': 'デザイン',
    'welcome.field.business': 'ビジネス',
    'welcome.field.marketing': 'マーケティング',
    'welcome.field.education': '教育',
    'welcome.field.healthcare': 'ヘルスケア',
    'welcome.button.join': 'コミュニティに参加',
    
    // Character Creator
    'character.title': 'キャラクターを作成',
    'character.subtitle': 'キャラクターをカスタマイズしてコミュニティに参加',
    'character.preview': 'プレビュー',
    'character.preview.placeholder': '猫を選択してプレビュー',
    'character.cat.type': '猫の種類',
    'character.outfit': '服装',
    'character.notselected': '未選択',
    'character.complete': 'キャラクター完成！',
    'character.button.back': '← 戻る',
    'character.button.join': '参加 →',
    
    // Cat Types
    'cat.tabby': 'トラ猫',
    'cat.tuxedo': 'タキシード猫',
    'cat.calico': '三毛猫',
    'cat.siamese': 'シャム猫',
    'cat.ginger': '茶トラ猫',
    'cat.white': '白猫',
    
    // Outfits
    'outfit.casual': 'カジュアル',
    'outfit.casual.desc': '快適でリラックス',
    'outfit.business': 'ビジネス',
    'outfit.business.desc': 'プロフェッショナル',
    'outfit.creative': 'クリエイティブ',
    'outfit.creative.desc': '芸術的でユニーク',
    'outfit.sporty': 'スポーティ',
    'outfit.sporty.desc': '活発でエネルギッシュ',
    'outfit.formal': 'フォーマル',
    'outfit.formal.desc': 'エレガントなスタイル',
    'outfit.tech': 'テック',
    'outfit.tech.desc': 'モダンでテクニカル',
    
    // Lobby Page
    'lobby.stats.title': 'ロビー情報',
    'lobby.stats.jobseekers': '求職中の人数',
    'lobby.stats.samefield': '同じ分野',
    'lobby.stats.focusing': '集中中',
    'lobby.stats.online': 'オンライン',
    'lobby.cat.dialogue': '25分間集中しましょう、新しいアクセサリーをあげます！',
    'lobby.focus.button.start': '25分集中を開始',
    'lobby.focus.button.focusing': '集中中... (25:00)',
    'lobby.focus.progress': '今日の進捗',
    'lobby.focus.complete': '🎉 今日の目標達成！',
    'lobby.focus.overlay': '集中中...',
    'lobby.others.title': '集中中の仲間',
    'lobby.others.minutes': '分',
    'lobby.messages.title': 'パブリックメッセージ',
    'lobby.messages.placeholder': '今やっていることを共有、例：OSラボをやっています',
    'lobby.messages.hint': '💡 ダミーデータを使用中、後でWebSocket/Redisに接続します',

    // About Page
    'about.title': 'Jobbo Catについて',
    'about.subtitle': 'コミュニティ主導のプラットフォームで、求職者を繋ぎ、意義ある職業的関係を育みます',
    'about.mission.title': '私たちの使命',
    'about.mission.p1': '就職活動は孤立し、圧倒されることがあります。Jobbo Catは、',
    'about.mission.highlight': 'あなたは一人じゃない',
    'about.mission.p2': 'という信念に基づいて構築されています。',
    'about.mission.p3': '私たちは、求職者が繋がり、経験を共有し、お互いをサポートし、意義ある職業的関係を築くことができる場を作ります。一緒に、就職活動の旅をより協力的で、恐れの少ないものにします。',
    'about.creator.title': 'クリエイターについて',
    'about.creator.name': 'Lianrui Sun（リアンルイ・サン）',
    'about.creator.role': 'フルスタック開発者＆プロダクトデザイナー',
    'about.creator.bio': 'スケーラブルなウェブアプリケーションの構築と直感的なユーザー体験の創造に専門知識を持つ情熱的な開発者。現在カナダを拠点とし、コンピュータサイエンスとソフトウェアエンジニアリングの強力なバックグラウンドを持つ。',
    'about.creator.education': '学歴：',
    'about.creator.education.value': 'コンピュータサイエンス学士、ウォータールー大学（2026年卒業予定）',
    'about.creator.skills': 'スキル：',
    'about.creator.skills.value': 'React、TypeScript、Node.js、Python、クラウドアーキテクチャ、UI/UXデザイン',
    'about.creator.experience': '経験：',
    'about.creator.experience.value': 'フルスタック開発、プロダクトデザイン、コミュニティ構築',
    'about.creator.quote': '"就職活動の困難を直接経験したからこそ、私が望んでいたサポーティブなコミュニティを作るためにJobbo Catを構築しました。一緒にこの旅を乗り越えましょう。"',
    'about.values.title': '私たちの価値観',
    'about.values.community.title': 'コミュニティ第一',
    'about.values.community.desc': '本物のつながりを築き、お互いをサポートする',
    'about.values.transparency.title': '透明性',
    'about.values.transparency.desc': 'オープンで正直なコミュニケーションとリアルタイムの可視性',
    'about.values.empowerment.title': 'エンパワーメント',
    'about.values.empowerment.desc': 'あなたの成功のためのツールとサポートを提供',

    // Features Page
    'features.title': '強力な機能',
    'features.subtitle': '求職の旅で成功するために必要なすべて',
    'features.live.title': 'リアルタイム訪問者数',
    'features.live.desc': '今何人オンラインかをリアルタイムで確認できます。あなたは一人じゃありません。',
    'features.auth.title': '安全な認証',
    'features.auth.desc': 'Supabaseによる安全なログイン。あなたのデータは保護され、プライバシーが尊重されます。',
    'features.character.title': 'キャラクターカスタマイズ',
    'features.character.desc': '独自の猫のキャラクターを作成します。種類、服、アクセサリーを選択し、自分を表現しましょう。',
    'features.profile.title': 'パーソナルプロフィール',
    'features.profile.desc': 'ユーザー名、経歴、キャラクターをカスタマイズ。自分を表現し、他の人とつながりましょう。',
    'features.focus.title': '集中セッション',
    'features.focus.desc': 'ポモドーロスタイルのタイマーで生産性を追跡。一貫した学習習慣を構築します。',
    'features.community.title': 'コミュニティサポート',
    'features.community.desc': 'あなたの分野の求職者とつながります。経験を共有し、お互いをサポートしましょう。',
    'features.multilang.title': '多言語サポート',
    'features.multilang.desc': '英語、スペイン語、日本語、韓国語、中国語（簡体字・繁体字）で利用可能です。',
    'features.responsive.title': '完全レスポンシブ',
    'features.responsive.desc': 'デスクトップ、タブレット、モバイルで完璧に動作します。いつでもどこでも学習できます。',
  },
  ko: {
    // Header
    'header.title': 'JobboCat',
    'header.features': '기능',
    'header.about': '소개',
    'header.login': '로그인',
    
    // Welcome Page
    'welcome.badge.loading': '로딩 중...',
    'welcome.badge.looking': '명이 지금 구직 중입니다',
    'welcome.badge.person': '명',
    'welcome.badge.first': '첫 번째 회원이 되세요!',
    'welcome.badge.youare': '당신은 #',
    'welcome.early.title': '얼리 어답터!',
    'welcome.early.message': '첫 10명의 회원 중 한 명입니다! 커뮤니티에 오신 것을 환영합니다! 🚀',
    'welcome.title': '당신은 혼자가 아닙니다',
    'welcome.subtitle': '같은 여정을 하는 사람들이 얼마나 되는지 확인하세요. 연결하고, 경험을 공유하고, 서로를 지원하세요.',
    'welcome.field.select': '분야 선택',
    'welcome.field.technology': '기술',
    'welcome.field.design': '디자인',
    'welcome.field.business': '비즈니스',
    'welcome.field.marketing': '마케팅',
    'welcome.field.education': '교육',
    'welcome.field.healthcare': '의료',
    'welcome.button.join': '커뮤니티 가입',
    
    // Character Creator
    'character.title': '고양이 캐릭터 만들기',
    'character.subtitle': '캐릭터를 커스터마이징하고 커뮤니티에 가입하세요',
    'character.preview': '미리보기',
    'character.preview.placeholder': '고양이를 선택하여 미리보기',
    'character.cat.type': '고양이 종류',
    'character.outfit': '의상',
    'character.notselected': '선택 안 됨',
    'character.complete': '캐릭터 완성!',
    'character.button.back': '← 뒤로',
    'character.button.join': '가입 →',
    
    // Cat Types
    'cat.tabby': '얼룩 고양이',
    'cat.tuxedo': '턱시도 고양이',
    'cat.calico': '삼색 고양이',
    'cat.siamese': '샴 고양이',
    'cat.ginger': '생강 고양이',
    'cat.white': '흰 고양이',
    
    // Outfits
    'outfit.casual': '캐주얼',
    'outfit.casual.desc': '편안하고 여유로운',
    'outfit.business': '비즈니스',
    'outfit.business.desc': '전문적인 룩',
    'outfit.creative': '크리에이티브',
    'outfit.creative.desc': '예술적이고 독특한',
    'outfit.sporty': '스포티',
    'outfit.sporty.desc': '활동적이고 활기찬',
    'outfit.formal': '포멀',
    'outfit.formal.desc': '우아한 스타일',
    'outfit.tech': '테크',
    'outfit.tech.desc': '현대적이고 기술적인',
    
    // Lobby Page
    'lobby.stats.title': '로비 정보',
    'lobby.stats.jobseekers': '구직 중인 사람들',
    'lobby.stats.samefield': '같은 분야',
    'lobby.stats.focusing': '집중 중',
    'lobby.stats.online': '온라인',
    'lobby.cat.dialogue': '25분 동안 집중하면 새로운 액세서리를 드릴게요!',
    'lobby.focus.button.start': '25분 집중 시작',
    'lobby.focus.button.focusing': '집중 중... (25:00)',
    'lobby.focus.progress': '오늘의 진행',
    'lobby.focus.complete': '🎉 오늘의 목표 달성!',
    'lobby.focus.overlay': '집중 중...',
    'lobby.others.title': '집중 중인 친구들',
    'lobby.others.minutes': '분',
    'lobby.messages.title': '공개 메시지',
    'lobby.messages.placeholder': '지금 하고 있는 것을 공유하세요, 예: OS 실습 중',
    'lobby.messages.hint': '💡 더미 데이터 사용 중, 나중에 WebSocket/Redis 연결 예정',

    // About Page
    'about.title': 'Jobbo Cat 소개',
    'about.subtitle': '커뮤니티 기반 플랫폼으로 구직자를 연결하고 의미 있는 전문적 관계를 육성합니다',
    'about.mission.title': '우리의 미션',
    'about.mission.p1': '구직은 고립되고 압도적일 수 있습니다. Jobbo Cat은',
    'about.mission.highlight': '당신은 혼자가 아니다',
    'about.mission.p2': '라는 믿음 위에 구축되었습니다.',
    'about.mission.p3': '우리는 구직자들이 연결하고, 경험을 공유하고, 서로를 지원하며, 의미 있는 전문적 관계를 구축할 수 있는 공간을 만듭니다. 함께, 구직 여정을 덜 위압적이고 더 협력적으로 만듭니다.',
    'about.creator.title': '크리에이터 소개',
    'about.creator.name': 'Lianrui Sun (리안루이 선)',
    'about.creator.role': '풀스택 개발자 & 프로덕트 디자이너',
    'about.creator.bio': '확장 가능한 웹 애플리케이션 구축과 직관적인 사용자 경험 창조에 전문 지식을 가진 열정적인 개발자입니다. 현재 캐나다에 거주하며 컴퓨터 과학 및 소프트웨어 공학에 대한 강력한 배경을 가지고 있습니다.',
    'about.creator.education': '학력:',
    'about.creator.education.value': '컴퓨터 과학 학사, 워털루 대학교 (2026년 졸업 예정)',
    'about.creator.skills': '기술:',
    'about.creator.skills.value': 'React, TypeScript, Node.js, Python, 클라우드 아키텍처, UI/UX 디자인',
    'about.creator.experience': '경험:',
    'about.creator.experience.value': '풀스택 개발, 프로덕트 디자인, 커뮤니티 구축',
    'about.creator.quote': '"구직의 어려움을 직접 경험했기에, 제가 바랐던 지원 커뮤니티를 만들기 위해 Jobbo Cat을 구축했습니다. 이 여정을 함께 헤쳐 나갑시다."',
    'about.values.title': '우리의 가치',
    'about.values.community.title': '커뮤니티 우선',
    'about.values.community.desc': '진정한 연결을 구축하고 서로를 지원',
    'about.values.transparency.title': '투명성',
    'about.values.transparency.desc': '개방적이고 정직한 커뮤니케이션과 실시간 가시성',
    'about.values.empowerment.title': '역량 강화',
    'about.values.empowerment.desc': '당신의 성공을 위한 도구와 지원 제공',

    // Features Page
    'features.title': '강력한 기능',
    'features.subtitle': '구직 여정에서 성공하기 위한 모든 것',
    'features.live.title': '실시간 방문자 수',
    'features.live.desc': '지금 몇 명이 온라인인지 실시간으로 확인하세요. 당신은 혼자가 아닙니다.',
    'features.auth.title': '안전한 인증',
    'features.auth.desc': 'Supabase로 안전한 로그인. 당신의 데이터는 보호되고 프라이버시는 존중됩니다.',
    'features.character.title': '캐릭터 커스터마이징',
    'features.character.desc': '나만의 고양이 캐릭터를 만드세요. 종류, 옷, 악세서리를 선택하고 자신을 표현하세요.',
    'features.profile.title': '개인 프로필',
    'features.profile.desc': '사용자 이름, 경력, 캐릭터를 커스터마이징. 자신을 표현하고 다른 사람들과 연결하세요.',
    'features.focus.title': '집중 세션',
    'features.focus.desc': '포모도로 스타일 타이머로 생산성을 추적하세요. 일관된 학습 습관을 구축합니다.',
    'features.community.title': '커뮤니티 지원',
    'features.community.desc': '당신의 분야의 구직자들과 연결하세요. 경험을 공유하고 서로를 지원하세요.',
    'features.multilang.title': '다국어 지원',
    'features.multilang.desc': '영어, 스페인어, 일본어, 한국어, 중국어(간체 및 번체)로 이용 가능합니다.',
    'features.responsive.title': '완전 반응형',
    'features.responsive.desc': '데스크톱, 태블릿, 모바일에서 완벽하게 작동합니다. 언제 어디서나 학습하세요.',
  },
  'zh-CN': {
    // Header
    'header.title': 'JobboCat',
    'header.features': '特点',
    'header.about': '关于',
    'header.login': '登录',
    
    // Welcome Page
    'welcome.badge.loading': '加载中...',
    'welcome.badge.looking': '人正在找工作',
    'welcome.badge.person': '人',
    'welcome.badge.first': '成为第一个加入的人！',
    'welcome.badge.youare': '你是第 #',
    'welcome.early.title': '早期采用者！',
    'welcome.early.message': '你是前10名成员之一！欢迎来到社区！🚀',
    'welcome.title': '你并不孤单',
    'welcome.subtitle': '看看有多少人在同样的旅程中。连接、分享经验并相互支持。',
    'welcome.field.select': '选择你的领域',
    'welcome.field.technology': '技术',
    'welcome.field.design': '设计',
    'welcome.field.business': '商业',
    'welcome.field.marketing': '营销',
    'welcome.field.education': '教育',
    'welcome.field.healthcare': '医疗保健',
    'welcome.button.join': '加入社区',
    
    // Character Creator
    'character.title': '创建你的猫咪角色',
    'character.subtitle': '自定义你的角色并加入社区',
    'character.preview': '角色预览',
    'character.preview.placeholder': '选择一只猫来预览',
    'character.cat.type': '猫咪类型',
    'character.outfit': '服装',
    'character.notselected': '未选择',
    'character.complete': '角色完成！',
    'character.button.back': '← 返回',
    'character.button.join': '加入社区 →',
    
    // Cat Types
    'cat.tabby': '虎斑猫',
    'cat.tuxedo': '燕尾服猫',
    'cat.calico': '三花猫',
    'cat.siamese': '暹罗猫',
    'cat.ginger': '橘猫',
    'cat.white': '白猫',
    
    // Outfits
    'outfit.casual': '休闲',
    'outfit.casual.desc': '舒适放松',
    'outfit.business': '商务',
    'outfit.business.desc': '专业外观',
    'outfit.creative': '创意',
    'outfit.creative.desc': '艺术独特',
    'outfit.sporty': '运动',
    'outfit.sporty.desc': '活跃有活力',
    'outfit.formal': '正式',
    'outfit.formal.desc': '优雅风格',
    'outfit.tech': '科技',
    'outfit.tech.desc': '现代科技',
    
    // Lobby Page
    'lobby.stats.title': 'Lobby 信息',
    'lobby.stats.jobseekers': '正在找工的人数',
    'lobby.stats.samefield': '相同领域的人数',
    'lobby.stats.focusing': '正在专注中',
    'lobby.stats.online': '在线人数',
    'lobby.cat.dialogue': '一起刷 25 分钟，等会给你抽一个新挂件！',
    'lobby.focus.button.start': '开始专注 25 分钟',
    'lobby.focus.button.focusing': '专注中... (25:00)',
    'lobby.focus.progress': '今日进度',
    'lobby.focus.complete': '🎉 今日目标已完成！',
    'lobby.focus.overlay': '专注中...',
    'lobby.others.title': '正在专注的小伙伴',
    'lobby.others.minutes': '分钟',
    'lobby.messages.title': '公共消息流',
    'lobby.messages.placeholder': '发一句你现在在做什么，比如：在写操作系统 lab',
    'lobby.messages.hint': '💡 先用假数据，将来接 WebSocket/Redis',

    // About Page
    'about.title': '关于 Jobbo Cat',
    'about.subtitle': '社区驱动的平台，连接求职者并培养有意义的专业关系',
    'about.mission.title': '我们的使命',
    'about.mission.p1': '求职可能是孤立和压倒性的。Jobbo Cat 建立在',
    'about.mission.highlight': '你并不孤单',
    'about.mission.p2': '的信念之上。',
    'about.mission.p3': '我们创建一个空间，让求职者可以连接、分享经验、相互支持并建立有意义的专业关系。一起，我们让求职之旅更少令人生畏，更加协作。',
    'about.creator.title': '认识创建者',
    'about.creator.name': 'Lianrui Sun（孙连睿）',
    'about.creator.role': '全栈开发者 & 产品设计师',
    'about.creator.bio': '一位充满热情的开发者，专长于构建可扩展的网络应用程序和创造直观的用户体验。目前居住在加拿大，拥有扎实的计算机科学和软件工程背景。',
    'about.creator.education': '教育背景：',
    'about.creator.education.value': '计算机科学学士，滑铁卢大学（预计2026年毕业）',
    'about.creator.skills': '技能：',
    'about.creator.skills.value': 'React、TypeScript、Node.js、Python、云架构、UI/UX设计',
    'about.creator.experience': '经验：',
    'about.creator.experience.value': '全栈开发、产品设计、社区建设',
    'about.creator.quote': '"亲身经历过求职的挑战，我构建了Jobbo Cat来创建我希望存在的支持性社区。让我们一起度过这段旅程。"',
    'about.values.title': '我们的价值观',
    'about.values.community.title': '社区优先',
    'about.values.community.desc': '建立真实的联系并相互支持',
    'about.values.transparency.title': '透明度',
    'about.values.transparency.desc': '开放、诚实的沟通和实时可见性',
    'about.values.empowerment.title': '赋能',
    'about.values.empowerment.desc': '为你的成功提供工具和支持',

    // Features Page
    'features.title': '强大的功能',
    'features.subtitle': '在求职旅程中取得成功所需的一切',
    'features.live.title': '实时访客数',
    'features.live.desc': '实时查看有多少人在线。你并不孤单。',
    'features.auth.title': '安全认证',
    'features.auth.desc': 'Supabase 提供安全登录。你的数据受到保护，隐私受到尊重。',
    'features.character.title': '角色定制',
    'features.character.desc': '创建你自己的猫角色。选择类型、服装和配饰，表达你自己。',
    'features.profile.title': '个人档案',
    'features.profile.desc': '自定义你的用户名、简介和角色。表达自己，与他人建立联系。',
    'features.focus.title': '专注时段',
    'features.focus.desc': '用番茄钟风格计时器追踪你的生产力。建立一致的学习习惯。',
    'features.community.title': '社区支持',
    'features.community.desc': '与你领域的求职者建立联系。分享经验，互相支持。',
    'features.multilang.title': '多语言支持',
    'features.multilang.desc': '支持英语、西班牙语、日语、韩语和中文（简体和繁体）。',
    'features.responsive.title': '完全响应式',
    'features.responsive.desc': '在桌面、平板和移动设备上完美运行。随时随地学习。',
  },
  'zh-TW': {
    // Header
    'header.title': 'JobboCat',
    'header.features': '特點',
    'header.about': '關於',
    'header.login': '登入',
    
    // Welcome Page
    'welcome.badge.loading': '載入中...',
    'welcome.badge.looking': '人正在找工作',
    'welcome.badge.person': '人',
    'welcome.badge.first': '成為第一個加入的人！',
    'welcome.badge.youare': '你是第 #',
    'welcome.early.title': '早期採用者！',
    'welcome.early.message': '你是前10名成員之一！歡迎來到社群！🚀',
    'welcome.title': '你並不孤單',
    'welcome.subtitle': '看看有多少人在同樣的旅程中。連接、分享經驗並相互支持。',
    'welcome.field.select': '選擇你的領域',
    'welcome.field.technology': '技術',
    'welcome.field.design': '設計',
    'welcome.field.business': '商業',
    'welcome.field.marketing': '行銷',
    'welcome.field.education': '教育',
    'welcome.field.healthcare': '醫療保健',
    'welcome.button.join': '加入社群',
    
    // Character Creator
    'character.title': '創建你的貓咪角色',
    'character.subtitle': '自訂你的角色並加入社群',
    'character.preview': '角色預覽',
    'character.preview.placeholder': '選擇一隻貓來預覽',
    'character.cat.type': '貓咪類型',
    'character.outfit': '服裝',
    'character.notselected': '未選擇',
    'character.complete': '角色完成！',
    'character.button.back': '← 返回',
    'character.button.join': '加入社群 →',
    
    // Cat Types
    'cat.tabby': '虎斑貓',
    'cat.tuxedo': '燕尾服貓',
    'cat.calico': '三花貓',
    'cat.siamese': '暹羅貓',
    'cat.ginger': '橘貓',
    'cat.white': '白貓',
    
    // Outfits
    'outfit.casual': '休閒',
    'outfit.casual.desc': '舒適放鬆',
    'outfit.business': '商務',
    'outfit.business.desc': '專業外觀',
    'outfit.creative': '創意',
    'outfit.creative.desc': '藝術獨特',
    'outfit.sporty': '運動',
    'outfit.sporty.desc': '活躍有活力',
    'outfit.formal': '正式',
    'outfit.formal.desc': '優雅風格',
    'outfit.tech': '科技',
    'outfit.tech.desc': '現代科技',
    
    // Lobby Page
    'lobby.stats.title': 'Lobby 資訊',
    'lobby.stats.jobseekers': '正在找工的人數',
    'lobby.stats.samefield': '相同領域的人數',
    'lobby.stats.focusing': '正在專注中',
    'lobby.stats.online': '線上人數',
    'lobby.cat.dialogue': '一起刷 25 分鐘，等會給你抽一個新掛件！',
    'lobby.focus.button.start': '開始專注 25 分鐘',
    'lobby.focus.button.focusing': '專注中... (25:00)',
    'lobby.focus.progress': '今日進度',
    'lobby.focus.complete': '🎉 今日目標已完成！',
    'lobby.focus.overlay': '專注中...',
    'lobby.others.title': '正在專注的小夥伴',
    'lobby.others.minutes': '分鐘',
    'lobby.messages.title': '公共訊息流',
    'lobby.messages.placeholder': '發一句你現在在做什麼，比如：在寫作業系統 lab',
    'lobby.messages.hint': '💡 先用假資料，將來接 WebSocket/Redis',

    // About Page
    'about.title': '關於 Jobbo Cat',
    'about.subtitle': '社群驅動的平台，連結求職者並培養有意義的專業關係',
    'about.mission.title': '我們的使命',
    'about.mission.p1': '求職可能是孤立和壓倒性的。Jobbo Cat 建立在',
    'about.mission.highlight': '你並不孤單',
    'about.mission.p2': '的信念之上。',
    'about.mission.p3': '我們創建一個空間，讓求職者可以連結、分享經驗、相互支持並建立有意義的專業關係。一起，我們讓求職之旅更少令人生畏，更加協作。',
    'about.creator.title': '認識創建者',
    'about.creator.name': 'Lianrui Sun（孫連睿）',
    'about.creator.role': '全端開發者 & 產品設計師',
    'about.creator.bio': '一位充滿熱情的開發者，專長於構建可擴展的網路應用程式和創造直觀的使用者體驗。目前居住在加拿大，擁有紮實的電腦科學和軟體工程背景。',
    'about.creator.education': '教育背景：',
    'about.creator.education.value': '電腦科學學士，滑鐵盧大學（預計2026年畢業）',
    'about.creator.skills': '技能：',
    'about.creator.skills.value': 'React、TypeScript、Node.js、Python、雲端架構、UI/UX設計',
    'about.creator.experience': '經驗：',
    'about.creator.experience.value': '全端開發、產品設計、社群建設',
    'about.creator.quote': '"親身經歷過求職的挑戰，我構建了Jobbo Cat來創建我希望存在的支持性社群。讓我們一起度過這段旅程。"',
    'about.values.title': '我們的價值觀',
    'about.values.community.title': '社群優先',
    'about.values.community.desc': '建立真實的連結並相互支持',
    'about.values.transparency.title': '透明度',
    'about.values.transparency.desc': '開放、誠實的溝通和即時可見性',
    'about.values.empowerment.title': '賦能',
    'about.values.empowerment.desc': '為你的成功提供工具和支援',

    // Features Page
    'features.title': '強大的功能',
    'features.subtitle': '在求職旅程中取得成功所需的一切',
    'features.live.title': '即時訪客數',
    'features.live.desc': '即時查看有多少人在線上。你並不孤單。',
    'features.auth.title': '安全認證',
    'features.auth.desc': 'Supabase 提供安全登入。你的資料受到保護，隱私受到尊重。',
    'features.character.title': '角色自訂',
    'features.character.desc': '創建你自己的貓角色。選擇類型、服裝和配飾，表達你自己。',
    'features.profile.title': '個人檔案',
    'features.profile.desc': '自訂你的使用者名稱、簡介和角色。表達自己，與他人建立連結。',
    'features.focus.title': '專注時段',
    'features.focus.desc': '用番茄鐘風格計時器追蹤你的生產力。建立一致的學習習慣。',
    'features.community.title': '社群支援',
    'features.community.desc': '與你領域的求職者建立連結。分享經驗，互相支持。',
    'features.multilang.title': '多語言支援',
    'features.multilang.desc': '支援英語、西班牙語、日語、韓語和中文（簡體和繁體）。',
    'features.responsive.title': '完全響應式',
    'features.responsive.desc': '在桌面、平板和行動裝置上完美運作。隨時隨地學習。',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
